<h1>Dashboard</h1>
<main id="dashboard">
    <section class="dashboard__section">
        <!-- <h2>Accès rapide</h2> -->
        <div class="dashboard-card dashboard-stock">
            <h3>Alerte Stock</h3>
            <?php foreach ($alerts as $alert) { ?>
                <p>
                    <span><i class="fa-solid fa-triangle-exclamation"></i><?= $alert['name'] ?></span>
                    <span>(<?= $alert['stock'] ?>)</span>
                </p>
            <?php } ?>
            <!-- <a class="link-btn" href="/cyclotron/Products/stock">Voir</a> -->
        </div>
        <div class="dashboard-card dashboard-employee">
            <h3>Employés du mois</h3>

            <?php foreach ($employees as $employee) { ?>
                <p>
                    <span><i class="fa-solid fa-award"></i><?= $employee["username"] ?></span>
                    <span><?= $employee["total"] ?>€</span>
                </p>
            <?php } ?>

            <!-- <a class="link-btn" href="/cyclotron/Products/stock">Voir</a> -->
        </div>
        <div class="dashboard-card dashboard-revenue">
            <h3>Chiffre d'affaire</h3>
            <p><span><i class="fa-solid fa-arrow-trend-up"></i>Mois en cours</span><span><?= $monthRevenues["totalByPeriod"] ?>€</span></p>
            <p><span><i class="fa-solid fa-arrow-trend-up"></i>Année en cours</span><span><?= $yearRevenues["totalByPeriod"] ?>€</span></p>
            <!-- <a class="link-btn" href="/cyclotron/Products/stock">Voir</a> -->
        </div>
    </section>
</main>