<h1>Répertoire des vendeurs</h1>

<main id="employees">
    <table class="table">
        <thead>
            <tr class="align-middle">
                <th scope="col">#</th>
                <th scope="col">Prénom</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 1;
            foreach ($users as $user) : ?>
                <tr class="align-middle">
                    <td><?= $i ?></td>
                    <td><?= $user['username'] ?></td>
                    <td class="text-end"><a href="/cyclotron/Users/salesBySeller/<?= $user['id'] ?>" type="button" class="btn btn-primary w-50">Consulter les résultats</button></td>
                </tr>
            <?php
                $i++;
            endforeach; ?>
        </tbody>
    </table>
    <div class="text-center m-5"><a class="btn btn-success p-3" href="/cyclotron/Users/employeesManagement">Ajouter un nouvel employé</a></div>

</main>