<h1>Répertoire des employés</h1>
<p class="mobile-message">Cette page n'est pas accessible depuis votre appareil, veuillez retourner à <a href="/cyclotron">l'accueil</a>.</p>

<main id="employees" class="mobile-hide">
    <table class="table">
        <thead>
            <tr class="align-middle">
                <th scope="col">#</th>
                <th scope="col">Prénom</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 1;
            foreach ($users as $user) : ?>
                <tr class="align-middle">
                    <td><?= $i ?></td>
                    <td><?= $user['username'] ?></td>
                    <td class="d-flex flex-column align-items-end">
                        <a href="/cyclotron/Users/salesBySeller/<?= $user['id'] ?>" type="button" class="btn btn-primary w-25 m-1">Consulter les résultats</a>

                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger w-25 m-1" data-bs-toggle="modal" data-bs-target="#modal<?= $i ?>">
                            Supprimer
                        </button>

                        <!-- Modal -->
                        <div class="modal" id="modal<?= $i ?>" tabindex="-1">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Êtes-vous sûr?</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <p>La suppression de cette utilisateur sera définitive.</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Annuler</button>
                                        <a href="/cyclotron/Users/deleteEmployee/<?= $user['id'] ?>" type="button" class="btn btn-danger">Confirmer</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php
                $i++;
            endforeach; ?>
        </tbody>
    </table>
    <div class="text-center m-5"><a class="btn btn-success p-3" href="/cyclotron/Users/employeesManagement">Ajouter un nouvel employé</a></div>

</main>