<h1>Création d'un nouvel employé</h1>

<main id="employees-management">
    <form action="/cyclotron/Users/createEmployee" method="POST">

        <div class="mb-3">
            <label for="username" class="form-label">Nom d'utilisateur : </label>
            <input required type="text" class="form-control" id="username" name="username" value="<?php if (isset($_POST["username"])) echo $_POST["username"] ?>">
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Adresse email : </label>
            <input required type="email" class="form-control" id="email" name="email" value="<?php if (isset($_POST["email"])) echo $_POST["email"] ?>">
        </div>
        <!-- <div class="text-center m-5"><a href="/cyclotron/Users/generatePassword/<?php if (isset($employee)) echo $employee['id']; ?>" class="btn btn-danger">Générer un mot de passe fort</a></div> -->
        <div class="mb-3">
            <select required class="form-select" name="employee_status">
                <option selected>Status de l'employé</option>
                <option value="1">Administrateur</option>
                <option value="2">Employé</option>
            </select>
        </div>


        <div class="text-center m-5"><button type="submit" class="btn btn-primary">Valider</button></div>
    </form>
</main>