<header class="index__header">
  <h1><?= $indexTitle ?></h1>
</header>
<main class="index__main">
  <form method="POST" action="/cyclotron/Users/login">
    <div class="input-container">
      <label class="input-container__label" for="username">Nom d'utilisateur :</label>
      <input class="input-container__input" type="text" id="username" name="username">
    </div>
    <div class="input-container">
      <label class="input-container__label" for="password">Mots de passe :</label>
      <input class="input-container__input" type="password" id="password" name="password">
    </div>
    <div class="btn-container"><button class="button" type="submit" name="submitLogin">Valider</button></div>
  </form>
</main>