<h1>Espace de connexion</h1>

<main id="index">
  <form method="POST" action="/cyclotron/Users/login">
    <div class="mb-3">
      <label class="form-label" for="account">Adresse email : </label>
      <input required class="form-control" type="email" id="account" name="account">
    </div>
    <div class="mb-3">
      <label class="form-label" for="password">Mots de passe : </label>
      <input required class="form-control" type="password" id="password" name="password">
    </div>
    <div class="text-center m-5"><button class="btn btn-primary" type="submit" name="submitLogin">Valider</button></div>
  </form>
</main>