<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?= $pageTitle ?></title>
  <link rel="stylesheet" href="/cyclotron/public/sass/main.css">
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> -->
  <script src="https://kit.fontawesome.com/7710422967.js" crossorigin="anonymous"></script>
</head>

<body>


  <div class="menu">
    <figure class="menu__logo">
      <img id="logo-desktop" src="/cyclotron/public/assets/cyclotron-desktop.svg" alt="Logo de l'entreprise">
      <img id="logo-mobile" src="/cyclotron/public/assets/cyclotron-mobile-2.svg" alt="Logo de l'entreprise">
    </figure>
    <?php if (isset($_SESSION['id'])) { ?>
      <nav id="link-container" class="menu__nav">
        <a href="/cyclotron"><i class="fa-solid fa-compass"></i>Dashboard</a>
        <a href="/cyclotron/Customers/displayCustomers"><i class="fa-solid fa-address-book"></i>Fichier clients</a>
        <a href="/cyclotron/Products/stock"><i class="fa-solid fa-box-open"></i>Produits</a>
        <?php if (isset($_SESSION['status']) && $_SESSION['status'] === "boss") { ?> <a href="/cyclotron/Users/salesView"><i class="fa-solid fa-user-check"></i>Employés</a> <?php } ?>
        <a href="/cyclotron/Users/logout"><i class="fa-solid fa-arrow-right-to-bracket"></i>Déconnexion</a>
      </nav>
    <?php } ?>
    <!-- Div pour évènement menu burger -->
    <div id="menu-burger">
      <span class="burger-top"></span>
      <span class="burger-middle"></span>
      <span class="burger-bottom"></span>
    </div>
  </div>

  <div id="wrap">
    <?= $pageContent; ?>
  </div>
  <script src="/cyclotron/public/js/menu-burger.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>

</html>