<h1 class="text-center m-2">Outil de génération de facture</h1>
<p class="mobile-message">Cette page n'est pas accessible depuis votre appareil, veuillez retourner à <a href="/cyclotron">l'accueil</a>.</p>

<main class="mobile-hide">
    <form action="/cyclotron/Invoice/insertInvoice/<?= $id ?>" method="POST" class="m-5">
        <div id="invoiceContainer">

        </div>
        <div class="text-center m-5">
            <button id="newRow" type="button" class="btn btn-secondary m-3">Ajouter une ligne</button>
            <button type="submit" class="btn btn-primary m-3" name="submitInvoice">Valider la facture</button>
        </div>
    </form>
</main>
<script src="/cyclotron/public/js/invoice.js"></script>