<h1>Chiffre d'affaire réalisé par : <?= $user['username'] ?></h1>

<main id="seller-sales" class="mobile-hide">
    <table class="table p-3 mt-5 mx-auto w-50">
        <thead>
            <tr>
                <th scope="col">Mois</th>
                <th scope="col" class="text-end">Total</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            <?php
            foreach ($resultByMonth as $result) {
            ?>
                <tr>
                    <td><?= $result['month'] ?></td>
                    <td class="text-end"><?= $result['total'] ?> €</td>
                </tr>
            <?php } ?>

            <tr>
                <th scope="row" class="fs-5">Total</th>
                <td class=" text-end fw-bold fst-italic fs-5"><?= $resultByYear ?> €</td>

            </tr>
        </tbody>
    </table>
</main>