<h1>Liste des stocks produit</h1>

<main id="stock-product">
    <table class="table">
        <thead>
            <tr class="align-middle">
                <th class="tablet-hide" scope="col">#</th>
                <th scope="col">Produit</th>
                <th scope="col" class="tablet-hide">Référence</th>
                <th scope="col">Stock</th>
                <th scope="col" class="mobile-hide">Prix</th>
                <?php if (isset($_SESSION['status']) && $_SESSION['status'] === '1') { ?><th scope="col"></th> <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 1;
            foreach ($products as $product) : ?>
                <tr <?php if ($product['stock'] <= $product['stock_alert']) : ?> class="table-danger align-middle" <?php endif ?> class="align-middle">
                    <th class="tablet-hide" scope="row"><?= $i ?></th>
                    <td><?= $product['name'] ?></td>
                    <td class="tablet-hide"><?= $product['reference'] ?></td>
                    <td><?= $product['stock'] ?></td>
                    <td class="mobile-hide"><?= $product['price_ht'] ?></td>
                    <?php if (isset($_SESSION['status']) && $_SESSION['status'] === '1') { ?> <td class="text-end"><a href="/cyclotron/Products/productsManagement/<?= $product['id'] ?>" type="button" class="btn btn-primary w-auto">Modifier</button></td> <?php } ?>
                </tr>
            <?php $i++;
            endforeach; ?>
        </tbody>
    </table>
</main>